
[build]
# Set the default target to match the Cortex-M0+ in the RP2040
target = "thumbv6m-none-eabi"

# Target specific options
[target.thumbv6m-none-eabi]
rustflags = ["-C", "link-args=-Tlink.x -Tlink-rp.x -Tdefmt.x"]
runner = "probe-rs run --chip RP2040"

[env]
DEFMT_LOG = "trace"

